# -*- coding: utf-8 -*-
"""UIDAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdAy9UdgVa7qEC0wBRDJaYjkkMw0BYrK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams["figure.figsize"] = (10,6)
sns.set_style("whitegrid")

from google.colab import files

uploaded = files.upload()

enrolment = pd.read_csv("enrolment.csv")
demographic = pd.read_csv("demographic_updates.csv")
biometric = pd.read_csv("biometric_updates.csv")

print(enrolment.head())
print(demographic.head())
print(biometric.head())

print(enrolment.head())
print(demographic.head())
print(biometric.head())

enrolment["date"] = pd.to_datetime(enrolment["date"], format="%d-%m-%Y")
demographic["date"] = pd.to_datetime(demographic["date"], format="%d-%m-%Y")
biometric["date"] = pd.to_datetime(biometric["date"], format="%d-%m-%Y")

enrolment.dropna(inplace=True)
demographic.dropna(inplace=True)
biometric.dropna(inplace=True)

for col in ["state","district"]:
    enrolment[col] = enrolment[col].str.strip().str.upper()
    demographic[col] = demographic[col].str.strip().str.upper()
    biometric[col] = biometric[col].str.strip().str.upper()

enrolment["total_enrolment"] = (
    enrolment["age_0_5"] +
    enrolment["age_5_17"] +
    enrolment["age_18_greater"]
)

enrolment_dist = enrolment.groupby(
    ["state","district"]
)[["age_0_5","age_5_17","age_18_greater","total_enrolment"]].sum().reset_index()

biometric_dist = biometric.groupby(
    ["state","district"]
)[["bio_age_5_17","bio_age_17_"]].sum().reset_index()

demographic_dist = demographic.groupby(
    ["state","district"]
)[["demo_age_5_17","demo_age_17_"]].sum().reset_index()

merged = enrolment_dist.merge(
    biometric_dist,
    on=["state","district"],
    how="inner"
)

merged = merged.merge(
    demographic_dist,
    on=["state","district"],
    how="inner"
)

merged.head()

merged["bio_update_rate_5_17"] = merged["bio_age_5_17"] / merged["age_5_17"]
merged["bio_update_rate_18"] = merged["bio_age_17_"] / merged["age_18_greater"]

age_totals = enrolment[["age_0_5","age_5_17","age_18_greater"]].sum()

age_totals.plot(kind="bar")
plt.title("Age-wise Aadhaar Enrolment")
plt.xlabel("Age Group")
plt.ylabel("Count")
plt.show()

bio_totals = biometric[["bio_age_5_17","bio_age_17_"]].sum()

bio_totals.plot(kind="bar")
plt.title("Biometric Updates by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Update Count")
plt.show()

merged["total_bio_updates"] = merged["bio_age_5_17"] + merged["bio_age_17_"]

top_districts = merged.sort_values(
    by="total_bio_updates",
    ascending=False
).head(10)

plt.bar(top_districts["district"], top_districts["total_bio_updates"])
plt.xticks(rotation=45)
plt.title("Top Districts by Biometric Updates")
plt.ylabel("Updates")
plt.show()

plt.scatter(
    merged["age_5_17"],
    merged["bio_age_5_17"],
    s=merged["demo_age_5_17"]/5
)
plt.xlabel("Enrolment Age 5-17")
plt.ylabel("Biometric Updates Age 5-17")
plt.title("Enrolment vs Biometric Updates (Bubble = Demographic Updates)")
plt.show()

biometric["year"] = biometric["date"].dt.year

yearly_bio = biometric.groupby("year")[["bio_age_5_17","bio_age_17_"]].sum()

yearly_bio.plot(marker="o")
plt.title("Year-wise Biometric Update Trend")
plt.xlabel("Year")
plt.ylabel("Update Count")
plt.show()

high_demand = merged[
    merged["total_bio_updates"] > merged["total_bio_updates"].mean()
]

high_demand[["state","district","total_bio_updates"]].head()

age_totals = enrolment[["age_0_5","age_5_17","age_18_greater"]].sum()

plt.figure()
age_totals.plot(kind="bar")
plt.title("Age-wise Aadhaar Enrolment")
plt.xlabel("Age Group")
plt.ylabel("Enrolment Count")
plt.tight_layout()
plt.show()

merged["total_bio_updates"] = merged["bio_age_5_17"] + merged["bio_age_17_"]

top_districts = merged.sort_values(
    by="total_bio_updates",
    ascending=False
).head(10)

plt.figure()
plt.bar(top_districts["district"], top_districts["total_bio_updates"])
plt.xticks(rotation=45)
plt.title("Top 10 Districts by Biometric Updates")
plt.xlabel("District")
plt.ylabel("Biometric Update Count")
plt.tight_layout()
plt.show()

plt.figure()
plt.scatter(
    merged["age_5_17"],
    merged["bio_age_5_17"],
    s=merged["demo_age_5_17"]/5,
    alpha=0.6
)
plt.xlabel("Enrolment (Age 5–17)")
plt.ylabel("Biometric Updates (Age 5–17)")
plt.title("Enrolment vs Biometric Updates (Bubble = Demographic Updates)")
plt.tight_layout()
plt.show()

